#!/usr/bin/env bash
# Tranfer a file to a server
if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
filepath=$1
ip=$2
ssh_path=$4
user=$3

scp -i "$ssh_path" -o StrictHostKeyChecking=no "$filepath" "$user"@"$ip":
