#!/usr/bin/env bash
# Install nginx web server
apt-get -y install nginx

# make nginx listen on port 80
sudo utf allow 'Nginx HTTP'

# serve hello world when configured 
custom_message="Hello World!"
nginx_config="/etc/nginx/sites-available/default"
sudo sed -i '/location \/ {/a \\t\treturn 200 "'"$custom_message"'";' "$nginx_config"

# restart nginx
sudo service nginx restart

