#!/usr/bin/env bash
# displays the username, user id, Home directory path for the user of /etc/passwd

while IFS=":" read -r username x uid gid gecos home shell;
do
	x=''
	gid=''
	gecos=''
	shell=''
	echo "$username:$uid:$home$x$gid$gecos$shell"
done < /etc/passwd
