#!/usr/bin/env bash
# 101-tell_the_story_of_passwd

while IFS=":" read -r user passwd uid gid gecos home shell
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
done < /etc/passwd
